# IRIS Dataset Analysis and Classification using Logistic Regression

A logistic regression model, made upon IRIS Dataset.

Made by Rishabhraj Srivastava.

In [2]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
# Loading the dataset from the link
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
data = pd.read_csv(url, names=columns)


In [4]:
# Exploring the dataset
data.head()
data.describe()
data["class"].value_counts()

# Splitting the dataset into features and target
X = data.iloc[:, :-1].values # features
y = data.iloc[:, -1].values # target

# Splitting the dataset into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# Creating and fitting the logistic regression model
model = LogisticRegression(multi_class="ovr", solver="liblinear")
model.fit(X_train, y_train)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [6]:
# Making predictions on the test set
y_pred = model.predict(X_test)

# Evaluating the model performance
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report:\n", classification_report(y_test, y_pred))



Accuracy score: 1.0
Confusion matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

